### ISSUE TITLE
starting transition to cordova-sqlite-evmax-eu-build-free - initial phase

### ISSUE THREAD

**Issue by brody2consult** [mobilexag/cordova-sqlite-evplus-ext-free#38]
As discussed by email, we want to transition away from this private fork towards a new evmax pluign version: https://github.com/brodybits/cordova-sqlite-evmax-eu-build-free

Here are the most important changes:

- evplus enhancements to support 90MB result data with (ugly) workaround, as was required by multiple customers
- evmax enhancements to support INSERTion of 200MB data over 1 million rows (another ugly workaround), as required by another customer
- support a new, non-standard `BLOBFROMBASE64` function as required for a customer working with MBTiles data
- evmax workaround to support slash (`/`) character with Capacitor, as required by a another, new customer

Here are the changes between this plugin version and `cordova-sqlite-evmax-eu-build-free`:

- https://github.com/brodybits/cordova-sqlite-evmax-eu-build-free/compare/evplus-eu-support-2022..master

with the following changes in the Android NDK library:

- https://github.com/brodybits/android-sqlite-evmax-ndk-driver-free/compare/evcore-eu-support-2022..evmax-eu-support-2023

TODO:

- [x] missing updates from SQLite `3.41.2` with some bug fixes _now included by `3.43.0`_ ref:
    - https://sqlite.org/releaselog/3_41_2.html
    - https://sqlite.org/src/timeline?from=version-3.41.1&to=version-3.41.2
- [x] bug fixes expected to be released in SQLite `3.41.3` _now included by `3.43.0`_ ref:
  - https://sqlite.org/src/timeline?from=version-3.41.2&to=branch-3.41
- [x] _update with recent SQLite `3.43.0` release ref: https://sqlite.org/releaselog/3_43_0.html_
- [x] _enable math functions ref: <https://www.sqlite.org/lang_mathfunc.html>_
- [ ] acceptance testing

**Comment by brody2consult** [comment]
I have just updated https://github.com/brodybits/cordova-sqlite-evmax-eu-build-free with SQLite `3.43.0` & math functions enabled, with `0.0.1-pre02` tag

**Comment by kryops** [comment]
Hi @brodybits ,

iOS is looking good, however on Android I noticed random freezes that occur after a few seconds or minutes of clicking through the app.

I tried a bit of debugging with medium success; here's my findings:

- It seems like either the native part does not send a response for one of the queries, or the JavaScript part does not handle it correctly. The `txLock` in the JavaScript code stays in progress and just queues all subsequent queries:

![image](https://github.com/mobilexag/cordova-sqlite-evplus-ext-free/assets/1042594/4eea3948-33b2-4fd0-bdeb-8254cbaa6b6e)

- The Java logic seems to be done (i.e. not stuck there). I made a thread dump, and it sits waiting at the line ` dbq = q.take();`:

```
"pool-10-thread-2@23553" prio=5 tid=0x12d nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	  at io.sqlc.SQLitePlugin$DBRunner.run(SQLitePlugin.java:541)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	  at java.lang.Thread.run(Thread.java:920)
```

- LogCat does not contain anything suspicious

Is there anything more that we can do on our end to locate the root cause?

Thanks for looking into it!

**Comment by brody2consult** [comment]
My understanding is that you observe this form of instability with the new evmax plugin version but NOT with this existing mobileX fork.

It would help me if you could test the stability with another plugin fork, which has no EU character support: https://github.com/storesafe/cordova-plugin-sqlite-evplus-ext-common-free

I am now wondering if there could be an issue my evmax workaround solution for 200 MB input data and something and your mobileX application.

**Comment by kryops** [comment]
That's correct, in the existing mobileX fork we did not observe this issue.

I just tested with https://github.com/storesafe/cordova-plugin-sqlite-evplus-ext-common-free#0.9.1-rc01, and I could reproduce the issue there as well.

**Comment by brody2consult** [comment]
That indicates to me that there is an issue somewhere between your application and the evplus enhancements in `cordova-plugin-sqlite-evplus-ext-common-free`. At this point I am suspecting an issue in the plugin, NOT in your application code. (Note that this plugin version never got the enhancements from `cordova-plugin-sqlite-evplus-ext-common-free` despite its "evplus" plugin name.)

It may help if you can give me an idea what kind of data it is getting stuck on. Here is my email address in case you don't have it on hand: chris.brody+brodybits@gmail.com

**Comment by kryops** [comment]
I tried to dig a little deeper: It seems that this affects queries with quite large result sets.

I observed two separate error cases in `SQLitePluginTransaction.prototype.run_batch_flatjson`:
1) The `result` does not end with a `"endrows"` item, so the loop runs infinitely and causes an out of memory because it keeps adding empty rows to the `rows` array

![image](https://github.com/mobilexag/cordova-sqlite-evplus-ext-free/assets/1042594/c89a2775-c946-45ee-985f-98c4f4a284be)

(I set a conditional breakpoint for `ri > 10000`)

![image](https://github.com/mobilexag/cordova-sqlite-evplus-ext-free/assets/1042594/9247dbf2-3db2-4c0d-ae58-711e59ca6f9d)

2) The `mycb` callback is called twice for the same query, but the `result` array only seems to be a slice of what we expect, and it does not start with `"okrows"`. Thus the whole result set is skipped and the callback in the user code is never called:

![image](https://github.com/mobilexag/cordova-sqlite-evplus-ext-free/assets/1042594/bd3db646-63dc-4890-84e2-61d9440087da)

I did not have much luck yet debugging further down in `SQLitePluginTransaction.prototype.run_batch_flat_with_dbid_part2`.

I also tried to build a minimal Cordova app with a reproduction, but had no luck either. Maybe we will end up sending you our actual app via e-mail so you can use it for debugging 😅

**Comment by brody2consult** [comment]
@kryops thanks for all of your efforts!

It seems to me like the result data has quite a number of columns with `null`, integer, and short string values. I will guess there may be some longer string values in the result columns as well.

I would like to do some testing on my own with a large number of columns with varying column data types & sizes and see how my evplus & evmax plugin versions hold up.

I would like to discuss some other options by private email with @DanielSWolf as well.

**Comment by brody2consult** [comment]
@kryops it may be helpful if you can give me a rough idea of how many columns may be in the result data and now many of the columns may have string length greater than 10 characters or so.

I will work on a test case to see how my evplus & evmax plugin versions work with such a large number of result columns. I will also follow up with @DanielSWolf by email, maybe later today.

**Comment by kryops** [comment]
@brodybits here are example rows from the two queries that seem to be the ones affected most:

```
committed: true
description: null
id: "12353"
installationDisplayId: null
installationId: null
installationShortText: null
locationDisplayId: "10224"
locationId: "14"
locationShortText: "Klinikum der Universität München"
notificationDisplayId: null
notificationId: null
notificationShortText: null
position: 1
workingState: "NOT_DONE"
```

```
assignmentId: "1251"
assignmentType: "SM01"
assignmentWorkflowStatus: "SEEN"
installationDisplayId: "10018863"
installationId: "5515"
installationMaterialNo: null
installationType: "M"
locationDisplayId: "10223"
locationId: "7"
notificationDate: "2017-04-28T12:21:53.000Z"
notificationId: "625"
notificationPriority: "2"
notificationStatus: "MAUF MIAR"
notificationType: "S2"
objectListItemDisplayId: "10018863"
objectListItemId: "12355"
orderActivityType: "001"
orderId: "774"
orderType: "SM02"
```

- `...ShortText` columns can have up to 40 characters
- `description` can be longer
- `...DisplayId` are usually 10 characters or shorter

**Comment by brody2consult** [comment]
Also rough estimate of how many result rows from each of the queries?

Thanks!

**Comment by kryops** [comment]
in this particular case it was 154 rows for both queries

**Comment by brody2consult** [comment]
Thanks. By design the result is split up and sent in parts, looks like something is not working right. I may need a few weeks to try these out.

**Comment by brody2consult** [comment]
~~I found a possible reproduction case,~~

__UPDATED & UPDATED DECEMBER 2025:__ _This test case ONLY reproduces an issue with error handling in case of not enough SQLite statement parameters which ends up with no response back to the JavaScript side - may discuss further in discussion comments coming up below; test comments added; test label, test db name, and other test comments updated to reflect actual situation with this test case_

(based on a reproduction I made for <https://github.com/storesafe/cordova-sqlite-storage-help/issues/70> from the past):

```js
        it(suiteName + 'INSERT JSON TEXT string many rows with hundred properties each with extra columns but with some missing columns', function(done) {
          var db = openDatabase('INSERT-JSON-TEXT-string-many-rows-with-hundred-properties-extra-columns-but-with-some-columns-missing.db')

          var test_rows = 700
          var test_props = 100

          db.transaction(function(tx) {
            tx.executeSql('DROP TABLE IF EXISTS test_table');
            tx.executeSql('CREATE TABLE IF NOT EXISTS test_table (data, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15)', [], function(ignored1, ignored2) {

              for (var id=0; id<test_rows; ++id) {
                var obj = {}

                obj.id = id;

                for (var i=0; i<test_props; ++i) {
                  obj['prop'+i] = 'value-'+(1000+i)
                }

                var insert_data = JSON.stringify(obj)

                // INCORRECT INSERT - MISSING MULTIPLE ARGUMENTS - NO RESPONSE TO JAVASCRIPT SIDE:
                tx.executeSql('INSERT INTO test_table VALUES (?,?,?,?,?,?,?,?)', [insert_data, null, 8881, null, 8882, null, 8883, 8884])
              }

              // INCORRECT INSERT - MISSING MANY ARGUMENTS - WILL REPORT AN ERROR IF INCORRECT INSERT IS FIXED ABOVE
              tx.executeSql('INSERT INTO test_table VALUES (?)', ['{extra:true}'], function(tx_ignored, rs1) {
                // NOT EXECUTED DUE TO INCORRECT INSERT
                expect(rs1).toBeDefined();
                expect(rs1.rowsAffected).toBe(1);

                tx.executeSql('SELECT * FROM test_table')
                tx.executeSql('SELECT * FROM test_table')
                tx.executeSql('SELECT * FROM test_table')
                tx.executeSql('SELECT * FROM test_table')
                tx.executeSql('SELECT * FROM test_table')
                tx.executeSql('SELECT data FROM test_table', [], function(tx_ignored, rs2) {
                  expect(rs2).toBeDefined();
                  expect(rs2.rows).toBeDefined();
                  // expect(rs2.rows.length).toBe(???);

                  var row = rs2.rows.item(0);
                  expect(row.data).toBeDefined() // [TBD (...)]

                  done();

                });
              });
            });
          }, function(error) {
            // ERROR RESULT
            expect(false).toBe(true);
            expect(error.message).toBe('---');
            // Close (plugin only) & finish:
            (isWebSql) ? done() : db.close(done, done);
          });
        }, MYTIMEOUT);
```

The new evmax plugin version freezes with this case; both `cordova-sqlite-evcore-extbuild-free` and the existing mobileX evplus fork end up with an internal batch error.

I would absolutely hope to support this case. I may need some time to investigate further and find a solution. Thanks.

**Comment by brody2consult** [comment]
~~__UPDATE DECEMBER 16 2025:__ The test case in this comment works for me on a more recent Android emulator, on my MacBook Pro.~~

The previous reproduction I made was incorrect due to not enough INSERT parameters, and it led to the frozen execution in the new evmax plugin version. I would like to resolve that, but I am not (yet) convinced that my previous reproduction covers the issue with your application.

I have made another test case that can successfully insert many records that I think should reflect the kind of data that your application inserts into the database, then tried selecting multiple times within the same transaction. In this case I am able to SELECT & ignore the data 3 times, uncomment the 4th time and it crashes on my emulator. (I have also added a commented-out line that reproduces the issue I found with not enough INSERT parameters.)

__NOTE THAT THE 4TH SELECT STATEMENT NEEDS TO BE UNCOMMENTED TO REPRODUCE THE CRASH__

```js
        it(suiteName + 'INSERT JSON TEXT string many rows with hundred properties each with extra columns & SELECT the data multiple times', function(done) {
          var db = openDatabase('INSERT-JSON-TEXT-string-many-rows-with-hundred-properties-extra-columns-and-select-data-multiple times.db')

          var test_rows = 7000
          var test_props = 100

          db.transaction(function(tx) {
            tx.executeSql('DROP TABLE IF EXISTS test_table');
            tx.executeSql('CREATE TABLE IF NOT EXISTS test_table (data, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15)', [], function(ignored1, ignored2) {

              for (var id=0; id<test_rows; ++id) {
                var obj = {}

                obj.id = id;

                for (var i=0; i<test_props; ++i) {
                  obj['prop'+i] = 'value-'+(1000+i)
                }

                var insert_data = JSON.stringify(obj)

                // INCORRECT INSERT - MISSING 2 ARGUMENTS - NO RESPONSE TO JAVASCRIPT SIDE:
                // tx.executeSql('INSERT INTO test_table VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)', [insert_data, 'abcdefghijklmnopqrst', null, 7771, 'abcdef', null, 71, 'abcdefghijklmnopqrst', null, 7771, 'abcdef', null, 71])
                // CORRECT INSERT:
                tx.executeSql('INSERT INTO test_table VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', [insert_data, 'abcdefghijklmnopqrst', null, 7771, 'abcdef', null, 71, 'abcdefghijklmnopqrst', null, 7771, 'abcdef', null, 71, 'abcdef', null])
              }

              tx.executeSql('INSERT INTO test_table VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', ['{extra:true}', null, 8881, null, 8882, null, 8883, 8884, 1, 1, 1, 1, 1, 1, 1], function(tx_ignored, rs1) {
                expect(rs1).toBeDefined();
                expect(rs1.rowsAffected).toBe(1);

                // SELECT & IGNORE:
                tx.executeSql('SELECT * FROM test_table')

                // SELECT & IGNORE - AGAIN & AGAIN:
                tx.executeSql('SELECT * FROM test_table')
                tx.executeSql('SELECT * FROM test_table')

                // UNCOMMENT FOR ONE MORE TIME CRASHES IN MY EMULATOR:
                // tx.executeSql('SELECT * FROM test_table')

                // SELECT & EXAMINE (just a little):
                tx.executeSql('SELECT data FROM test_table', [], function(tx_ignored, rs2) {
                  expect(rs2).toBeDefined();
                  expect(rs2.rows).toBeDefined();
                  // expect(rs2.rows.length).toBe(???);

                  var row = rs2.rows.item(0);
                  expect(row.data).toBeDefined() // [TBD (...)]

                  done();

                });
              });
            });
          }, function(error) {
            // NOT EXPECTED:
            expect(false).toBe(true);
            expect(error.message).toBe('---');
            // Close (plugin only) & finish:
            (isWebSql) ? done() : db.close(done, done);
          });
        }, MYTIMEOUT);
```

I would really love to get all of these cases working, still need to investigate further before promising any timelines.

**Comment by brody2consult** [comment]
@kryops wrote in <https://github.com/mobilexag/cordova-sqlite-evplus-ext-free/issues/38#issuecomment-1706812517>:
> 1. The `result` does not end with a `"endrows"` item, so the loop runs infinitely and causes an out of memory because it keeps adding empty rows to the `rows` array
> 
> ![image](https://private-user-images.githubusercontent.com/1042594/265742865-c89a2775-c946-45ee-985f-98c4f4a284be.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU5MzM0MDcsIm5iZiI6MTc2NTkzMzEwNywicGF0aCI6Ii8xMDQyNTk0LzI2NTc0Mjg2NS1jODlhMjc3NS1jOTQ2LTQ1ZWUtOTg1Zi05OGM0ZjRhMjg0YmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMTdUMDA1ODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTU5ODllZTI4Mjg3MTk5MjhmOWYzYmMzZjdiNzY2NWU1NjE1NjlkYjEwMzliNTA3YWZiNjQ4YzVmMGIzMmFmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.UekRFtkya54GFS6gbf4Tk9-jaDaoTgl42Z8iRji4ojY)
> 
> (I set a conditional breakpoint for `ri > 10000`)
> 
> ![image](https://private-user-images.githubusercontent.com/1042594/265742758-9247dbf2-3db2-4c0d-ae58-711e59ca6f9d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU5MzM0MDcsIm5iZiI6MTc2NTkzMzEwNywicGF0aCI6Ii8xMDQyNTk0LzI2NTc0Mjc1OC05MjQ3ZGJmMi0zZGIyLTRjMGQtYWU1OC03MTFlNTljYTZmOWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMTdUMDA1ODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQ0N2ZkMmRlOTJlMTUxOTEwZWEyOWE2YTYyZjM1YjUyZDQ4ZWFjNWExY2MyNTIzMjVkZjI2NjIxNzM2ZmZhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ICvjkXMf0TFxBpJdk2_YBUpqDlaPve_DB6uoGFJYuX0)
> 
> 2. The `mycb` callback is called twice for the same query, but the `result` array only seems to be a slice of what we expect, and it does not start with `"okrows"`. Thus the whole result set is skipped and the callback in the user code is never called:
> 
> ![image](https://private-user-images.githubusercontent.com/1042594/265743551-bd3db646-63dc-4890-84e2-61d9440087da.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU5MzM0MDcsIm5iZiI6MTc2NTkzMzEwNywicGF0aCI6Ii8xMDQyNTk0LzI2NTc0MzU1MS1iZDNkYjY0Ni02M2RjLTQ4OTAtODRlMi02MWQ5NDQwMDg3ZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMTdUMDA1ODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmU2NzRjYWMzZTBmYThkZDA2MDMyYWUxNzhhOTRhNWRkNDM3YjYzZjBhY2ZiNWM0MzEzNGFmOTcwMjYxMGYwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Uo-ve87AEokCjg1ht4vEiTP4KtbSWYByn3jE4xOzr8E)
>[...]

~~After looking through the C, Java, and JavaScript code _it looks to me like_ this is an issue on the JavaScript side. It _appears_ to me like the JavaScript code does not _properly_ handle the split-up result callbacks with the result rows in multiple parts _in certain cases_. I suspect this _could_ affect other evmax _and potentially other evplus_ plugin versions.~~

I think the best solution would be to _further investigate the issue(s)_ & fix the JavaScript code to _properly handle_ all parts of the result rows ... this could take some more time for development & unit testing.

A quicker way forward _which has been rejected during private email correspondence_ may be to simply increase the result chunk cutoff in the C code say 5x or 10x in the EU support branch & verify that this is OK during the integration testing. This should be considered a temporary workaround until I get a chance to implement a better solution (someday).

---

I did find a couple other issues as commented with test cases above. I am hiding these for now to help keep this discussion as focused as possible. While I would love ot resolve these someday, I would like to defer this for now.

I would also like to apologize for posting a useless draft that may show up in the email notification, which I have already deleted to keep things as clear & focused as I can for now.

---

~~__UPDATES:__ What I wrote did not did not seem to properly reflect the state of the existing JavaScript code (which is generated from CoffeeScript v1 code); I updated the text to hopefully reflect the state more properly. My "quicker way forward" was rejected by private email correspondence. My next step is to investigate the JavaScript further to find the proper solution.~~

---

__NEW UPDATE:__ After further looking through the layers of C, JavaScript, and Java code I could not identify anything that should suffer from issues with the split-up result chunks. I am now suspecting that the testing observations from @kryops are due to issues between the Cordova plugin "keep callback" feature, internal Cordova JS <==> native bridge, etc. that I have not been able to reproduce so far. I would like to discuss some idea(s) in further comments below.

**Comment by brody2consult** [comment]
After pouring more deeply though the C, Java & JavaScript code, I could not find anything that could explain the issues observed by @kryops.

I have also tried an updated test case _for the evmax plugin version_ pasted below, and noticed that the callback came with some missing rows ~~exactly once~~ _a couple times_ out of many test runs in my emulator. ~~There are some commented-out variations with even heavier data I/O which have consistently crashed in my mobile emulator.~~

I am now suspecting that there is some kind of intermittent issue in the Cordova JavaScript <==> native bridge when using the cordova-android `PluginResult.setKeepCallback()` method.

At this point I am thinking to rework the evmax plugin version so that the JavaScript side would explicitly request each one of the chunks of a large result. I think this should decrease the chances of missing & broken-up results. This may have a slightly higher JavaScript <==> native communication cost, which I think should be very minimal if not truly negligible.

I am also hopeful about being able to handle the even larger amounts of INSERT & SELECT result data without crashing.

---

Updated test case that did show me some missing result rows ~~exactly once~~ _a couple times_ in my emulator (on the evmax plugin version):

```js
        it(suiteName + 'INSERT JSON TEXT string many rows with hundred properties each in JSON TEXT & extra columns; then SELECT the data multiple times', function(done) {
          var db = openDatabase('INSERT-JSON-TEXT-string-many-rows-with-hundred-json-text-properties-extra-columns-then-select-data-multiple times.db')

          // XXX TBD MAY ADJUST NUMBER OF TEST ROWS AS NEEDED IN FUTURE TESTING
          // NOTE: INCREASING TEST ROWS to 35000 CAUSES CRASH ON BOTH EMULATOR & DEVICE
          var test_rows = 30000
          var test_props = 100

          db.transaction(function(tx) {
            tx.executeSql('DROP TABLE IF EXISTS test_table');
            tx.executeSql('CREATE TABLE IF NOT EXISTS test_table (data, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15)', [], function(ignored1, ignored2) {

              for (var id=0; id<test_rows; ++id) {
                var obj = {}

                obj.id = id;

                for (var i=0; i<test_props; ++i) {
                  obj['prop'+i] = 'value-'+(1000+i)
                }

                var insert_data = JSON.stringify(obj)

                // CORRECT INSERT:
                tx.executeSql('INSERT INTO test_table VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', [insert_data, 'abcdefghijklmnopqrst', null, 7771, 'abcdef', null, 71, 'abcdefghijklmnopqrst', null, 7771, 'abcdef', null, 71, 'abcdef', null])
              }

              tx.executeSql('INSERT INTO test_table VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', ['{extra:true}', null, 8881, null, 8882, null, 8883, 8884, 1, 1, 1, 1, 1, 1, 1], function(tx_ignored, rs1) {
                expect(rs1).toBeDefined();
                expect(rs1.rowsAffected).toBe(1);

                // TRY SELECT & IGNORE - UNCOMMENTING CAUSES CRASH ON BOTH EMULATOR & DEVICE
                // tx.executeSql('SELECT * FROM test_table')

                // SELECT & EXAMINE (just a little):
                tx.executeSql('SELECT data FROM test_table', [], function(tx_ignored, rs2) {
                  expect(rs2).toBeDefined();
                  expect(rs2.rows).toBeDefined();
                  // TBD ... ...
                  // expect(rs2.rows.length).toBe( /* ... */ );

                  var row = rs2.rows.item(0);
                  expect(row.data).toBeDefined() // [TBD (...)]

                  tx.executeSql('SELECT data FROM test_table', [], function(tx_ignored, rs3) {
                    expect(rs3).toBeDefined();
                    expect(rs3.rows).toBeDefined();
                    // XXX XXX
                    // TBD ... ...
                    // expect(rs3.rows.length).toBe( /* ... */ );

                    // XXX TBD UNCOMMENT TO STOP TEST HERE
                    // return done();

                    tx.executeSql('SELECT data FROM test_table', [], function(tx_ignored, rs4) {
                      expect(rs4).toBeDefined();
                      expect(rs4.rows).toBeDefined();
                      // XXX KNOWN TEST ERROR THAT SHOWS ACTUAL NUMBER OF ROWS
                      expect(rs4.rows.length).toBe('rs4 ---');

                      done();
                    });
                  });
                });
              });
            });
          }, function(error) {
            // NOT EXPECTED:
            expect(false).toBe(true);
            expect(error.message).toBe('---');
            // Close (plugin only) & finish:
            (isWebSql) ? done() : db.close(done, done);
          });
        }, MYTIMEOUT);
```

~~NOTE that this test case has incorrect & misleading label & open database name, also with irrelevant & garbage comments, just pasting this in as-is which gave me missing result rows exactly once in my emulator.~~

---

__UPDATES:__

- I cleaned up the test case above to improve comments, test label, and test database name. I saw the issue with some result rows before cleaning up the test case.
- I tried this test case on a device in Browser Stack, crashes when I uncomment the extra SELECT & IGNORE even on super high-end Samsung S25 Ultra device
- Increasing the number of test rows to 35000 also causes crash on test device in Browser Stack, even on the super high-end Samsung S25 Ultra device

---

__UPDATED STATUS:__

- I am now suspecting that using the `PluginResult.setKeepCallback()` method in the Java code for Android can lead to some flakey behavior under heavy data I/O in the cordova-android JavaScript <==> native bridge.
- Either adding the extra SELECT & ignore step or increasing the number of test rows to 35000 leads to crash consistently both on my emulator and on multiple devices in Browser Stack. I suspect that this is testing the limits somewhere between the JavaScript, Java, and JNI code, NOT any limits that may vary between various emulators & devices.
- I am thinking that updating the plugin code for the JavaScript to request the result chunks one at a time should avoid the flakiness observed with heavy data I/O. I am also hopeful that this update can help avoid the crashes I observed under the increased number of test rows & extra SELECT data load.

**Comment by brody2consult** [comment]
I have pushed a WIP branch with some quick DRAFT updates to stop using `PluginResult.setKeepCallback ()`: https://github.com/storesafe/cordova-sqlite-evmax-build-free/tree/brody-stop-using-keep-callback-wipsave1

I am hopeful that this will improve the stability during integration testing, which I may request in the near future.

Unfortunately the test continued to crash when further increasing the data load. While this does not seem to be an issue in production yet, I would love to support even heavier data loads in the future.

**Comment by brody2consult** [comment]
Closing in favor of moving forward with new discussion: https://github.com/storesafe/cordova-sqlite-evmax-build-free/issues/9
